jazzy \
  --readme ./docs/documentation-readme.md \
  --hide-documentation-coverage \
  --objc \
  --clean \
  --author "Data Theorem" \
  --author_url https://datatheorem.github.io \
  --github_url https://github.com/datatheorem/TrustKit \
  --github-file-prefix https://github.com/datatheorem/TrustKit/tree/1.4.1 \
  --module-version 1.4.1 \
  --umbrella-header TrustKit/TrustKit.h \
  --framework-root . \
  --module TrustKit \
  --output docs/documentation