# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'TrustKitDemo-ObjC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TrustKitDemo
  pod 'TrustKit', :path => '../'

end


target 'TrustKitDemo-Swift' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TrustKitDemo
  pod 'TrustKit', :path => '../'

end
